export const catalogoObject = () => {
  return {
    consultas: [
      {
        codigo: "0101",
        descripcion: "Examen-Diagnostico-Fichado y plan de tratamiento",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0103",
        descripcion: "visita a domicilio",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0104",
        descripcion:
          "consulta de urgencia que no constituya paso intermedio de tratamiento",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0105",
        descripcion: "consulta periodica preventiva",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
    ],
    operatoria: [
      {
        codigo: "0201",
        descripcion: "obturacion con amalgama cavidad simple",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0202",
        descripcion: "obturacion con amalgama cavidad compuesta",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0203",
        descripcion: "obturacion con amalgama cavidad compleja",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0204",
        descripcion: "reconstruccion de angulos con tornillo en conducto",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0209",
        descripcion:
          "reconstruccion de angulos con material estetico en dientes anteriores",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0215",
        descripcion: "restauracion c/mat. estetico simple en anteriores",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0216",
        descripcion: "restauracion c/mat. estetico compuesta en anteriores",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0217",
        descripcion: "restauracion c/mat. estetico compleja en anteriores",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0219",
        descripcion: "blanqueamiento externo en consultorio (por sesion)",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0220",
        descripcion: "blanqueamiento ambulatorio",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
    ],
    endodoncia: [
      {
        codigo: "0301",
        descripcion: "tratamiento pulpar de 1 conducto",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0302",
        descripcion: "tratamiento pulpar de 2 conducto",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0303",
        descripcion: "tratamiento pulpar de 3 conducto",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0304",
        descripcion: "tratamiento pulpar de 4 conducto",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0305",
        descripcion: "biopulpectomia parcial",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0306",
        descripcion: "necropulpectomia parcial(momificacion)",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0307",
        descripcion: "proteccion pulpar indirecta",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "0308",
        descripcion: "retratamiento conservador",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
    ],
    protesis: [
      {
        codigo: "040101",
        descripcion: "incrustacion cavidad simple",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040102",
        descripcion: "incrustacion cavidad compuesta",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040103",
        descripcion: "corona forjada",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040104",
        descripcion: "corona colada",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040105",
        descripcion: "corona colada c/ frente estetico de acrilico",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040106",
        descripcion: "corona espiga",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040108",
        descripcion: "perno muñon simple",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040109",
        descripcion: "perno muñon seccionado",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040110",
        descripcion: "tramo de puente colado",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040111",
        descripcion: "corona en acrilico",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040112",
        descripcion: "elemento provisorio de acrilico",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040113",
        descripcion: "corona de porcelana sobre metal",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040114",
        descripcion:
          "tramo de puente de porcelana sobre metal por elemento a reemplazar c/u",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040115",
        descripcion: "corona de porcelana pura",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040116",
        descripcion:
          "tramo de puente de porcelana por elemento a reemplazar c/u",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040117",
        descripcion: "corona de porcelana sobre zirconio",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040118",
        descripcion: "tramo de puente de porcelana sobre zirconio",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040119",
        descripcion: "extraccion de un perno",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040120",
        descripcion: "extraccion de una corona",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040121",
        descripcion: "incrustacion de resina",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040122",
        descripcion: "incrustacion de ceramica",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040123",
        descripcion: "carillas de resina",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040124",
        descripcion: "carillas de porcelana",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040125",
        descripcion: "perno de fibra de vidrio",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040101",
        descripcion: "protesis parcial de acrilico hasta 5 elementos",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040102",
        descripcion: "protesis parcial de acrilico",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040103",
        descripcion: "protesis parcial de cromo cobalto hasta 5 elementos",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
      {
        codigo: "040104",
        descripcion: "cementado perno / corona",
        costos_variables: "$2500",
        costos_fijos: "2000",
        costo_taller: "...",
        costo_total: "$4500",
        honor_prof: "3000",
        total_arancel: "7500",
      },
    ],
  }
}
